### ISSUE TITLE
remove unwrap in build.rs

### ISSUE THREAD

**Issue by xMAC94x** [rust-lang-nursery/lazy-static.rs#121] opened 2018-09-22 22:39 UTC
Dear Devs, i currently had a bug in the version_check crate  which causes lazy_static not to compile.
Having some env. variables set makes version_check fail. and in build.rs we have a unwrap() on the version.
May i ask what would happen when the rustc version is below 1.22 ? if it would fail anyway why do we need the unwrap here at all ?
However, if there is a good reason for the unwrap, i see the version check is only important if the nightly feature is disables. so you we just make the unwrap only in case nightly is disables ? e.g.

```rust
    let version_geq_122 = version_check::is_min_version("1.22.0");
    let drop_in_static_supported = nightly_feature_enabled || version_geq_122.unwrap().0;
```
this way we wouldnt call the unwrap when nightly_feature_enabled is true.

Thank you very much

**Comment by BurntSushi** [comment] 2018-09-22 22:49
Can you show an example of how to reproduce the bug that causes a build failure?

**Comment by KodrAus** [comment] 2018-09-24 08:27
Hi @xMAC94x, are you able to build `lazy-static` now that a patch of `version_check` has been released?

**Comment by KodrAus** [comment] 2018-09-26 23:11
Thanks again for the report @xMAC94x, I'll go ahead and close this one now because I think we'll keep the `unwrap` behaviour for now. If it becomes a bigger problem in the future then we'll work out what we want to do about it then.

**Closed by KodrAus** 2018-09-26 23:11 UTC
